export const EPISODES_NAMES = {
  "À la volette": "À la volette",
  Ablutions: "Ablutions",
  "Agnus dei": "Agnus dei",
  Always: "Always",
  Ambidextrie: "Ambidextrie",
  Amen: "Amen",
  "Anges et démons": "Anges et démons",
  Anton: "Anton",
  "Arthur et la question": "Arthur et la question",
  "Arthur et les ténèbres": "Arthur et les ténèbres",
  "Arthur in love": "Arthur in love",
  "Arthur sensei": "Arthur sensei",
  "Arturi inquisitio": "Arturi inquisitio",
  "Arturi inquisito": "Arturi inquisitio",
  "Arturus rex": "Arturus Rex",
  "Au bonheur des dames": "Au bonheur des dames",
  "Au service de sa majesté": "Au service secret de sa majesté",
  "Au service secret de sa majesté": "Au service secret de sa majesté",
  "Aux yeux de tous ii": "Aux yeux de tous II",
  "Aux yeux de tous iii": "Aux yeux de tous III",
  Basidiomycètes: "Basidiomycètes",
  Centurio: "Centurio",
  "Chante sloubi": "Chante sloubi",
  "Codes et stratégies": "Codes et stratégies",
  "Corpore sano": "Corpore sano",
  "Corpore sano ii": "Corpore sano II",
  "Corvus corone": "Corvus corone",
  "Court-métrage": "Court-métrage",
  "Cryda de tintagel": "Cryda de Tintagel",
  "Cuisine et dépendances": "Cuisine et dépendances",
  "Dagonet et le cadastre": "Dagonet et le cadastre",
  "De retour de judée": "De retour de Judée",
  "Décibels nocturnes": "Décibels nocturnes",
  "Dies irae": "Dies irae",
  "Diner dansant": "Dîner dansant",
  "Dîner dansant": "Dîner dansant",
  "Domi nostrae": "Domi nostrae",
  "Duel 2 partie": "Duel II",
  "Dux bellorum": "Dux bellorum",
  "Dux belorum": "Dux bellorum",
  "En forme de graal": "En forme de graal",
  Enluminures: "Enluminures",
  "Excalibur et le destin": "Excalibur et le destin",
  Exectuor: "Executor",
  Executor: "Executor",
  "Feu l'âne de guethenoc": "Feue l'âne de Guethenoc",
  "Feue la poule de guethenoc": "Feue la poule de Guethenoc",
  "Feue la vache de roparzh": "Feue la vache de Roparzh",
  "Fluctuat nec mergitur": "Fluctuat nec mergitur",
  "Goustan le cruel": "Goustan le cruel",
  "Guenievre et les oiseaux": "Guenievre et les oiseaux",
  Haunted: "Haunted",
  Heat: "Heat",
  "Hollow man": "Hollow man",
  Hurlement: "Hurlements",
  Hurlements: "Hurlements",
  "Immaculé karadoc": "Immaculé Karadoc",
  Jizo: "Jizô",
  Jizô: "Jizô",
  "L'absent": "L'absent",
  "L'absolution": "L'absolution",
  "L'abstinent": "L'abstinent",
  "L'alliance": "L'alliance",
  "L'ambition": "L'ambition",
  "L'ancien temps": "L'ancien temps",
  "L'approbation": "L'approbation",
  "L'arche de transport": "L'arche de transport",
  "L'art de la table": "L'art de la table",
  "L'assassin de kaamelott": "L'assassin de kaamelott",
  "L'assemblée des rois 1 partie": "L'assemblée des rois",
  "L'assemblée des rois 2 partie": "L'assemblée des rois II",
  "L'assemblée des rois 2e partie": "L'assemblée des rois II",
  "L'avènement du sanguinaire": "L'avènement du sanguinaire",
  "L'aveu de bohort": "L'aveu de Bohort",
  "L'échange 1 partie": "L'échange",
  "L'échelle de perceval": "L'échelle de Perceval",
  "L'élu": "L'élu",
  "L'empressée": "L'empressée",
  "L'enlèvement de guenievre": "L'enlèvement de Guenièvre",
  "L'enlèvement de guenièvre": "L'enlèvement de Guenièvre",
  "L'entente cordiale": "L'entente cordiale",
  "L'épée des rois": "L'épée des rois",
  "L'escorte": "L'escorte",
  "L'escorte ii": "L'escorte II",
  "L'espion": "L'espion",
  "L'etudiant": "L'étudiant",
  "L'étudiant": "L'étudiant",
  "L'expurgation de merlin": "L'expurgation de merlin",
  "L'habitué": "L'habitué",
  "L'imposteur": "L'imposteur",
  "L'inspiration": "L'inspiration",
  "L'interprète": "L'interprète",
  "L'invincible": "L'invincible",
  "L'ivresse": "L'ivresse",
  "L'oubli": "L'oubli",
  "La baliste": "La baliste",
  "La barraka": "La barraka",
  "La blessure d'yvain": "La blessure d'Yvain",
  "La blessure mortelle": "La blessure mortelle",
  "La botte secrète": "La botte secrète",
  "La botte secrète ii": "La botte secrète II",
  "La casette ii": "La cassette II",
  "La cassette": "La cassette",
  "La cassette ii": "La cassette II",
  "La chambre": "La chambre",
  "La chambre de la reine": "La chambre de la reine",
  "La chevalerie": "La chevalerie",
  "La clandestine": "La clandestine",
  "La coccinelle de madenn": "La coccinelle de madenn",
  "La conspiratrice": "La conspiratrice",
  "La corne d'abondance": "La corne d'abondance",
  "La dame et le lac": "La dame et le lac",
  "La délégation maure": "La délégation maure",
  "La démission": "La démission",
  "La dent de requin": "La dent de requin",
  "La dispute": "La dispute",
  "La dispute 2eme partie": "La dispute II",
  "La dispute i": "La dispute I",
  "La dispute ii": "La dispute II",
  "La fête de l'hiver": "La fête de l'hiver",
  "La fête du printemps": "La fête du printemps",
  "La foi bretonne": "La foi bretonne",
  "La fureur du dragon": "La fureur du dragon",
  "La garde royale": "La garde royale",
  "La grande bataille": "La grande bataille",
  "La joute ancillaire": "La joute ancillaire",
  "La jupe de calogrenant": "La jupe de Calogrenant",
  "La kleptomane": "La kleptomane",
  "La menace fantôme": "La menace fantôme",
  "La mission": "La mission",
  "La nourrice": "La nourrice",
  "La parade": "La parade",
  "La pâte d'amande": "La pâte d'amande",
  'La poétique "iième partie': "La poétique II",
  "La poétique ii": "La poétique II",
  "La poétique, 1 partie": "La poétique",
  "La potion de fécondité": "La potion de fécondité",
  "La potion de fécondité ii": "La potion de fécondité II",
  "La promesse": "La promesse",
  "La quête des deux renards": "La quête des deux renards",
  "La queue du scorpion": "La queue du scorpion",
  "La quinte juste": "La quinte juste",
  "La réaffectation": "La réaffectation",
  "La relève": "La relève",
  "La rémanence": "La rémanence",
  "La rencontre": "La rencontre",
  "La réponse": "La réponse",
  "La restriction": "La restriction",
  "La restriction ii": "La restriction II",
  "La retraite": "La retraite",
  "La révolte": "La révolte",
  "La révolte iii": "La révolte III",
  "La révoquée": "La révoquée",
  "La roche et le fer": "La roche et le fer",
  "La romance de lancelot": "La romance de Lancelot",
  "La ronde": "La ronde",
  "La sorcière": "La sorcière",
  "La supplique": "La supplique",
  "La table de breccan": "La table de Breccan",
  "La tarte aux fraises": "La tarte aux fraises",
  "La tarte aux myrtilles": "La tarte aux myrtilles",
  "La taxe militaire": "La taxe militaire",
  "La veillée": "La veillée",
  "La visite d'ygerne": "La visite d'Ygerne",
  "La vraie nature du graal": "La vraie nature du graal",
  Lacrimosa: "Lacrimosa",
  "Le banquet des chefs": "Le banquet des chefs",
  "Le cadeau": "Le cadeau",
  "Le cas yvain": "Le cas Yvain",
  "Le chaudron rutilant": "Le chaudron rutilant",
  "Le chevalier errant": "Le chevalier errant",
  "Le chevalier femme": "Le chevalier femme",
  "Le choix de gauvain": "Le choix de Gauvain",
  "Le code de chevalerie": "Le code de chevalerie",
  "Le complot": "Le complot",
  "Le coup d'épée": "Le coup d'épée",
  "Le culte secret": "Le culte secret",
  "Le dernier empereur": "Le dernier empereur",
  "Le dernier jour": "Le dernier jour",
  "Le dernier recours": "Le dernier recours",
  "Le déserteur": "Le déserteur",
  "Le désordre et la nuit": "Le désordre et la nuit",
  "Le destitué": "Le destitué",
  "Le dialogue de paix": "Le dialogue de paix",
  "Le dialogue de paix ii": "Le dialogue de paix II",
  "Le discobole": "Le discobole",
  "Le donneur": "Le donneur",
  "Le dragon des tunnels": "Le dragon des tunnels",
  "Le duel": "Le duel",
  "Le fléau de dieu": "Le fléau de dieu",
  "Le fléau de dieu ii": "Le fléau de dieu II",
  "Le forfait": "Le forfait",
  "Le garçon qui criait au loup": "Le garçon qui criait au loup",
  "Le grand départ": "Le grand départ",
  "Le guet": "Le guet",
  "Le jeu de la guerre": "Le jeu de la guerre",
  "Le jeu du caillou": "Le jeu du caillou",
  "Le jour d'alexandre": "Le jour d'Alexandre",
  "Le jurisconsulte": "Le jurisconsulte",
  "Le labyrinthe": "Le labyrinthe",
  "Le larcin": "Le larcin",
  "Le législateur": "Le législateur",
  "Le magnanime": "Le magnanime",
  "Le maître d'armes": "Le maître d'armes",
  "Le mangonneau": "Le mangonneau",
  "Le médiateur": "Le médiateur",
  "Le message codé": "Le message codé",
  "Le monde d'arthur": "Le monde d'arthur",
  "Le oud ii": "Le oud II",
  "Le pain": "Le pain",
  "Le paladin": "Le paladin",
  "Le passage secret": "Le passage secret",
  "Le pédagogue": "Le pédagogue",
  "Le périple": "Le périple",
  "Le petit poucet": "Le petit poucet",
  "Le poème": "Le poème",
  "Le porte bonheur": "Le porte bonheur",
  "Le portrait": "Le portrait",
  "Le privilégié": "Le privilégié",
  'Le privilégié"': "Le privilégié",
  "Le problème du chou": "Le problème du chou",
  "Le prodige du fakir": "Le prodige du fakir",
  "Le professionnel": "Le professionnel",
  "Le rapport": "Le rapport",
  "Le rassemblement du corbeau": "Le rassemblement du corbeau",
  "Le rassemblement du corbeau ii": "Le rassemblement du corbeau II",
  "Le rebelle": "Le rebelle",
  "Le reclassement": "Le reclassement",
  "Le refuge": "Le refuge",
  "Le renfort magique": "Le renfort magique",
  "Le renoncement  =1ère partie": "Le renoncement",
  "Le renoncement 2ème partie": "Le renoncement II",
  "Le répurgateur": "Le répurgateur",
  "Le retour de judée": "Le retour de judée",
  "Le retour du roi": "Le retour du roi",
  "Le rêve d'ygerne": "Le rêve d'Ygerne",
  "Le royaume sans tête": "Le royaume sans tête",
  "Le sacrifice": "Le sacrifice",
  "Le sanglier de cornouailles": "Le sanglier de cornouailles",
  "Le sauvetage": "Le sauvetage",
  "Le secret d'arthur": "Le secret d'Arthur",
  "Le secret de lancelot": "Le secret de Lancelot",
  "Le signe": "Le signe",
  "Le sixième sens": "Le sixième sens",
  "Le sort perdu": "Le sort perdu",
  "Le terroriste": "Le terroriste",
  "Le tourment": "Le tourment",
  "Le tourment ii": "Le tourment II",
  "Le tourment iii": "Le tourment III",
  "Le traitre": "Le traitre",
  "Le trouble": "Le trouble",
  "Le vice de forme": "Le vice de forme",
  Legenda: "Legenda",
  "Les affranchis": "Les affranchis",
  "Les alchimistes": "Les alchimistes",
  "Les aquitains": "Les aquitains",
  "Les biens nommés": "Les biens nommés",
  "Les bonnes": "Les bonnes",
  "Les chaperons": "Les chaperons",
  "Les cheveux noirs": "Les cheveux noirs",
  "Les chiens de guerre": "Les chiens de guerre",
  "Les classes de bohort": "Les classes de Bohort",
  "Les clous de la sainte croix": "Les clous de la sainte croix",
  "Les dauphins": "Les dauphins",
  "Les défis de merlin": "Les défis de Merlin",
  "Les défis de merlin ii": "Les défis de Merlin II",
  "Les embusqués": "Les embusqués",
  "Les envahisseurs": "Les envahisseurs",
  "Les esclaves": "Les esclaves",
  "Les exilés": "Les exilés",
  "Les exploités": "Les exploités",
  "Les exploités ii": "Les exploités II",
  "Les félicitations": "Les félicitations",
  "Les fesses de guenièvre": "Les fesses de Guenièvre",
  "Les festivités": "Les festivités",
  "Les fruits d'hiver": "Les fruits d'hiver",
  "Les fruits d'hivers": "Les fruits d'hiver",
  "Les liaisons dangereuses": "Les liaisons dangereuses",
  "Les mauvaises graines": "Les mauvaises graines",
  "Les misanthropes": "Les misanthropes",
  "Les neiges éternelles": "Les neiges éternelles",
  "Les nocturnales": "Les nocturnales",
  "Les nouveaux clans": "Les nouveaux clans",
  "Les nouveaux frères": "Les nouveaux frères",
  "Les novices": "Les novices",
  "Les paris ii": "Les paris II",
  "Les pionniers": "Les pionniers",
  "Les pisteurs": "Les pisteurs",
  "Les plaques de dissimulation": "Les plaques de dissimulation",
  "Les recruteurs": "Les recruteurs",
  "Les repentant": "Les repentant",
  "Les repentants": "Les repentants",
  "Les rivales": "Les rivales",
  "Les suppléants": "Les suppléants",
  "Les tartes aux myrtilles": "La tarte aux myrtilles",
  "Les tourelles": "Les tourelles",
  "Les transhumants": "Les transhumants",
  "Les tuteurs": "Les tuteurs",
  "Les tuteurs ii": "Les tuteurs II",
  "Les voeux": "Les voeux",
  "Les volontaires ii": "Les volontaires II",
  "Loth et le graal": "Loth et le graal",
  "Mater dixit": "Mater dixit",
  "Merlin l'archaïque": "Merlin l'archaïque",
  "Miles ignotus": "Miles ignotus",
  "Miles ingnotus": "Miles ignotus",
  Mission: "Mission",
  Monogame: "Monogame",
  Morituri: "Morituri",
  "Neiges éternelles": "Neiges éternelles",
  Nuptiae: "Nuptiae",
  "O'brother": "O'brother",
  "Patience dans la plaine": "Patience dans la plaine",
  "Perceval de sinope": "Perceval de sinope",
  "Perceval et le contre-sirop": "Perceval et le contre-sirop",
  "Perceval fait raitournelle": "Perceval fait raitournelle",
  "Plus près de toi": "Plus près de toi",
  "Plusieurs épisodes de la saison v": "Plusieurs épisodes de la saison V",
  Poltergeist: "Poltergeist",
  Polymorphe: "Polymorphie",
  Polymorphie: "Polymorphie",
  "Potion de fécondité": "La potion de fécondité",
  Praeceptores: "Praeceptores",
  Preaceptores: "Praeceptores",
  "Promotion de la série": "Promotion de la série",
  "Raison d'argent ii": "Raison d'argent II",
  "Raisons et sentiments": "Raisons et sentiments",
  "Réplique souvent répétée": "Réplique souvent répétée",
  "Saponides et detergents": "Saponides et détergents",
  "Saponides et détergents": "Saponides et détergents",
  "Sefriane d'aquitaine": "Séfriane d'aquitaine",
  "Séfriane d'aquitaine": "Séfriane d'aquitaine",
  "Seigneur caius": "Seigneur Caïus",
  "Seigneur caïus": "Seigneur Caïus",
  "Seli et les rongeurs": "Séli et les rongeurs",
  "Séli et les rongeurs": "Séli et les rongeurs",
  "Sept cent quarante-quatre": "Sept cent quarante-quatre",
  "Sequence souterraine": "Sequence souterraine",
  "Silbury hill": "Silbury hill",
  "Sous les verrous": "Sous les verrous",
  Spagenhelm: "Spangenhelm",
  Spangenhelm: "Spangenhelm",
  Spiritueux: "Spiritueux",
  Stargate: "Stargate",
  Teaser: "Teaser",
  "Tel un chevalier": "Tel un chevalier",
  "The game": "The game",
  "Tous les matins du monde": "Tous les matins du monde",
  "Tous les matins du monde (première partie)": "Tous les matins du monde",
  "Tous les matins du monde ii": "Tous les matins du monde II",
  "Tous les matins du monde, 2 partie": "Tous les matins du monde II",
  "Tous les matins du monde, 2ème partie": "Tous les matins du monde II",
  "Trois cent soixante degrés": "Trois cent soixante degrés",
  "Un bruit dans la nuit": "Un bruit dans la nuit",
  "Un roi à la taverne": "Un roi à la taverne",
  "Un roi à la taverne ii": "Un roi à la taverne II",
  Unagi: "Unagi",
  "Unagi ii": "Unagi II",
  "Unagi iv": "Unagi IV",
  "Unagi v": "Unagi V",
  "Vae soli !": "Vae soli !",
  "Vae soli!": "Vae soli !",
  "Vox populi ii": "Vox populi II",
  "Vox populi iii": "Vox populi III",
  Witness: "Witness",
} as const;
